- name: Node.js
  logo: nodedotjs
  url: 'https://nodejs.org/'
  color: '#339933'
  projects:
    - url: 'https://github.com/CodeHole7/React.js-Login-Form'
    
- name: Python
  logo: python
  url: 'https://www.python.org/'
  color: '#3C78A9'
  projects:
    - url: 'https://github.com/CodeHole7/knapsack-algorithm-python'
