  
name: 📚 Generate Tech Stack

on:
  workflow_dispatch: # Manual dispatch
  push:
    branches: [ master ]
    paths: [ assets/stack.yml ]
  schedule:
    - cron: '0 18 * * 3' # At 01:00 on Sunday.

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master
        with:
          path: assets/stack.yml
