name: 💠 3D Contrib Pattern

on:
  schedule: # every 12 hours
    - cron: "0 18 * * 4"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email devphs513@gmail.com
          git add -A .
          git commit -m "💠 Updtaes 3D contribution pattern"
          git push